name = "DocumenterResolveXRefInMainPrototype"
uuid = "ec50b518-6c18-4c34-be22-4983b883f12d"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MarkdownAST = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"

[compat]
Documenter = "1.3.0"
